<?php
/*
Description: Theme Setup
Theme: DECA
*/

// GLOBAL THEME SETUP
add_action( 'init', 'un_theme_setup' );

function un_theme_setup() {

	// Content Width
	if ( ! isset( $content_width ) ) {
		$content_width = 1200;
	}
		
	// Feed Links
	add_theme_support( 'automatic-feed-links' );
	
	
	// Post Thumbnails
	add_theme_support( 'post-thumbnails', array( 'post', 'product', 'un-portfolio', 'un-case-studies' ) );
	
	
	// Post Formats
	add_theme_support( 'post-formats', array( 'link', 'video' ) );
	
	
	// HTML5 
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'widgets' ) );
	
	
	// WP Title
	add_theme_support( 'title-tag' );
	
	
	// Custom Image Sizes
	// Live Feature (AQ_RESIZER)
	
	
	// Woocommerce Support
	add_theme_support( 'woocommerce' );
	
	
	// Shortcode Support
	add_filter('widget_text', 'do_shortcode');	
	
	
	// Standard Sidebars (Blog, Page, Footer 1-4)
	$un_blog_sidebar = array(
        'name'          => esc_html__( 'Blog', 'deca'),
        'id'            => 'un-blog-sidebar',
        'description' => 'Appears in the blog page and single posts.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	);
	
	$un_page_sidebar = array(
        'name'          => esc_html__( 'Page', 'deca'),
        'id'            => 'un-page-sidebar',
        'description' => 'Appears in all pages.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	); 
	
	$un_foot1_sidebar = array(
        'name'          => esc_html__( 'Footer 1', 'deca'),
        'id'            => 'un-foot1-sidebar',
        'description' => 'Appears always in the footer area.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	); 
	
	$un_foot2_sidebar = array(
        'name'          => esc_html__( 'Footer 2', 'deca'),
        'id'            => 'un-foot2-sidebar',
        'description' => 'Appears always in the footer area.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	); 
	
	$un_foot3_sidebar = array(
        'name'          => esc_html__( 'Footer 3', 'deca'),
        'id'            => 'un-foot3-sidebar',
        'description' => 'Appears in the footer area only if you select 3 or 4 columns in the options of the theme. This widget has a background white fixed.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	);

    $un_foot4_sidebar = array(
        'name'          => esc_html__( 'Footer 4', 'deca'),
        'id'            => 'un-foot4-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
    );
	
	$un_extra1_sidebar = array(
        'name'          => esc_html__( 'Extra 1', 'deca'),
        'id'            => 'un-extra1-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	); 
	
	$un_extra2_sidebar = array(
        'name'          => esc_html__( 'Extra 2', 'deca'),
        'id'            => 'un-extra2-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	); 
	
	$un_extra3_sidebar = array(
        'name'          => esc_html__( 'Extra 3', 'deca'),
        'id'            => 'un-extra3-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
	);

    $un_extra4_sidebar = array(
        'name'          => esc_html__( 'Extra 4', 'deca'),
        'id'            => 'un-extra4-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
    );
	
	$un_shop_sidebar = array(
        'name'          => esc_html__( 'Shop', 'deca'),
        'id'            => 'un-shop-sidebar',
        'description' => 'Use this area for extra custom widget.',
        'before_widget' => '<div class="un-wdg-w">',
        'after_widget'  => '</div>',
        'before_title'  =>  '<h6 class="un-wdg-t">',
        'after_title'   =>  '</h6>',
    );
	
	register_sidebar( $un_shop_sidebar );
	register_sidebar( $un_blog_sidebar );
	register_sidebar( $un_page_sidebar );
	
	// Check Footer Options
	
	register_sidebar( $un_foot1_sidebar );
	register_sidebar( $un_foot2_sidebar );
	register_sidebar( $un_foot3_sidebar );
    register_sidebar( $un_foot4_sidebar );
	
	register_sidebar( $un_extra1_sidebar );
	register_sidebar( $un_extra2_sidebar );
	register_sidebar( $un_extra3_sidebar );
    register_sidebar( $un_extra4_sidebar );
	
	
	// The Excerpt Lenght
	add_filter('excerpt_length', 'un_excerpt_length');
	
	function un_excerpt_length($length) {
	
		return 28; //todo
		
	}

	
	// Loading Feature
	if( !un_redux_opt(UN, 'opt-header-search', true) ){
		
		// Add "un-no-src" Class to Body
		add_filter( 'body_class', 'un_no_src' );
		
		function un_no_src( $classes ) {
			$classes[] = 'un-no-src';
			return $classes;
		}
		
	}
	

}


// Shop Menu Location
add_action( 'after_setup_theme', 'un_main_menu_location' );
function un_main_menu_location() {
  register_nav_menu( 'main-menu', esc_html__( 'Main Menu', 'deca' ) );
}



/***********/
/* HELPERS */
/***********/				
				
// LINEA Icons for iconpickers										
add_filter( 'vc_iconpicker-type-linea', 'un_iconpicker_type_linea' );

function un_iconpicker_type_linea( $icons )
{
    $linea_icons = array(
        array('un-l-icon-uniE000' => esc_html__('', 'deca')),
        array('un-l-icon-uniE001' => esc_html__('', 'deca')),
        array('un-l-icon-uniE002' => esc_html__('', 'deca')),
        array('un-l-icon-uniE003' => esc_html__('', 'deca')),
        array('un-l-icon-uniE004' => esc_html__('', 'deca')),
        array('un-l-icon-uniE005' => esc_html__('', 'deca')),
        array('un-l-icon-uniE006' => esc_html__('', 'deca')),
        array('un-l-icon-uniE007' => esc_html__('', 'deca')),
        array('un-l-icon-uniE008' => esc_html__('', 'deca')),
        array('un-l-icon-uniE009' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE00F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE010' => esc_html__('', 'deca')),
        array('un-l-icon-uniE011' => esc_html__('', 'deca')),
        array('un-l-icon-uniE012' => esc_html__('', 'deca')),
        array('un-l-icon-uniE013' => esc_html__('', 'deca')),
        array('un-l-icon-uniE014' => esc_html__('', 'deca')),
        array('un-l-icon-uniE015' => esc_html__('', 'deca')),
        array('un-l-icon-uniE016' => esc_html__('', 'deca')),
        array('un-l-icon-uniE017' => esc_html__('', 'deca')),
        array('un-l-icon-uniE018' => esc_html__('', 'deca')),
        array('un-l-icon-uniE019' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE01F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE020' => esc_html__('', 'deca')),
        array('un-l-icon-uniE021' => esc_html__('', 'deca')),
        array('un-l-icon-uniE022' => esc_html__('', 'deca')),
        array('un-l-icon-uniE023' => esc_html__('', 'deca')),
        array('un-l-icon-uniE024' => esc_html__('', 'deca')),
        array('un-l-icon-uniE025' => esc_html__('', 'deca')),
        array('un-l-icon-uniE026' => esc_html__('', 'deca')),
        array('un-l-icon-uniE027' => esc_html__('', 'deca')),
        array('un-l-icon-uniE028' => esc_html__('', 'deca')),
        array('un-l-icon-uniE029' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE02F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE030' => esc_html__('', 'deca')),
        array('un-l-icon-uniE031' => esc_html__('', 'deca')),
        array('un-l-icon-uniE032' => esc_html__('', 'deca')),
        array('un-l-icon-uniE033' => esc_html__('', 'deca')),
        array('un-l-icon-uniE034' => esc_html__('', 'deca')),
        array('un-l-icon-uniE035' => esc_html__('', 'deca')),
        array('un-l-icon-uniE036' => esc_html__('', 'deca')),
        array('un-l-icon-uniE037' => esc_html__('', 'deca')),
        array('un-l-icon-uniE038' => esc_html__('', 'deca')),
        array('un-l-icon-uniE039' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE03F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE040' => esc_html__('', 'deca')),
        array('un-l-icon-uniE041' => esc_html__('', 'deca')),
        array('un-l-icon-uniE042' => esc_html__('', 'deca')),
        array('un-l-icon-uniE043' => esc_html__('', 'deca')),
        array('un-l-icon-uniE044' => esc_html__('', 'deca')),
        array('un-l-icon-uniE045' => esc_html__('', 'deca')),
        array('un-l-icon-uniE046' => esc_html__('', 'deca')),
        array('un-l-icon-uniE047' => esc_html__('', 'deca')),
        array('un-l-icon-uniE048' => esc_html__('', 'deca')),
        array('un-l-icon-uniE049' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE04F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE050' => esc_html__('', 'deca')),
        array('un-l-icon-uniE051' => esc_html__('', 'deca')),
        array('un-l-icon-uniE052' => esc_html__('', 'deca')),
        array('un-l-icon-uniE053' => esc_html__('', 'deca')),
        array('un-l-icon-uniE054' => esc_html__('', 'deca')),
        array('un-l-icon-uniE055' => esc_html__('', 'deca')),
        array('un-l-icon-uniE056' => esc_html__('', 'deca')),
        array('un-l-icon-uniE057' => esc_html__('', 'deca')),
        array('un-l-icon-uniE058' => esc_html__('', 'deca')),
        array('un-l-icon-uniE059' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE05F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE060' => esc_html__('', 'deca')),
        array('un-l-icon-uniE061' => esc_html__('', 'deca')),
        array('un-l-icon-uniE062' => esc_html__('', 'deca')),
        array('un-l-icon-uniE063' => esc_html__('', 'deca')),
        array('un-l-icon-uniE064' => esc_html__('', 'deca')),
        array('un-l-icon-uniE065' => esc_html__('', 'deca')),
        array('un-l-icon-uniE066' => esc_html__('', 'deca')),
        array('un-l-icon-uniE067' => esc_html__('', 'deca')),
        array('un-l-icon-uniE068' => esc_html__('', 'deca')),
        array('un-l-icon-uniE069' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE06F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE070' => esc_html__('', 'deca')),
        array('un-l-icon-uniE071' => esc_html__('', 'deca')),
        array('un-l-icon-uniE072' => esc_html__('', 'deca')),
        array('un-l-icon-uniE073' => esc_html__('', 'deca')),
        array('un-l-icon-uniE074' => esc_html__('', 'deca')),
        array('un-l-icon-uniE075' => esc_html__('', 'deca')),
        array('un-l-icon-uniE076' => esc_html__('', 'deca')),
        array('un-l-icon-uniE077' => esc_html__('', 'deca')),
        array('un-l-icon-uniE078' => esc_html__('', 'deca')),
        array('un-l-icon-uniE079' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE07F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE080' => esc_html__('', 'deca')),
        array('un-l-icon-uniE081' => esc_html__('', 'deca')),
        array('un-l-icon-uniE082' => esc_html__('', 'deca')),
        array('un-l-icon-uniE083' => esc_html__('', 'deca')),
        array('un-l-icon-uniE084' => esc_html__('', 'deca')),
        array('un-l-icon-uniE085' => esc_html__('', 'deca')),
        array('un-l-icon-uniE086' => esc_html__('', 'deca')),
        array('un-l-icon-uniE087' => esc_html__('', 'deca')),
        array('un-l-icon-uni61' => esc_html__('', 'deca')),
        array('un-l-icon-uni62' => esc_html__('', 'deca')),
        array('un-l-icon-uni63' => esc_html__('', 'deca')),
        array('un-l-icon-uni64' => esc_html__('', 'deca')),
        array('un-l-icon-uni65' => esc_html__('', 'deca')),
        array('un-l-icon-uni66' => esc_html__('', 'deca')),
        array('un-l-icon-uni67' => esc_html__('', 'deca')),
        array('un-l-icon-uni68' => esc_html__('', 'deca')),
        array('un-l-icon-uni69' => esc_html__('', 'deca')),
        array('un-l-icon-uni6A' => esc_html__('', 'deca')),
        array('un-l-icon-uni6B' => esc_html__('', 'deca')),
        array('un-l-icon-uni6C' => esc_html__('', 'deca')),
        array('un-l-icon-uni6D' => esc_html__('', 'deca')),
        array('un-l-icon-uni6E' => esc_html__('', 'deca')),
        array('un-l-icon-uni6F' => esc_html__('', 'deca')),
        array('un-l-icon-uni70' => esc_html__('', 'deca')),
        array('un-l-icon-uni71' => esc_html__('', 'deca')),
        array('un-l-icon-uni72' => esc_html__('', 'deca')),
        array('un-l-icon-uni73' => esc_html__('', 'deca')),
        array('un-l-icon-uni74' => esc_html__('', 'deca')),
        array('un-l-icon-uni75' => esc_html__('', 'deca')),
        array('un-l-icon-uni76' => esc_html__('', 'deca')),
        array('un-l-icon-uni77' => esc_html__('', 'deca')),
        array('un-l-icon-uni78' => esc_html__('', 'deca')),
        array('un-l-icon-uni79' => esc_html__('', 'deca')),
        array('un-l-icon-uni7A' => esc_html__('', 'deca')),
        array('un-l-icon-uni41' => esc_html__('', 'deca')),
        array('un-l-icon-uni42' => esc_html__('', 'deca')),
        array('un-l-icon-uni43' => esc_html__('', 'deca')),
        array('un-l-icon-uni44' => esc_html__('', 'deca')),
        array('un-l-icon-uni45' => esc_html__('', 'deca')),
        array('un-l-icon-uni46' => esc_html__('', 'deca')),
        array('un-l-icon-uni47' => esc_html__('', 'deca')),
        array('un-l-icon-uni48' => esc_html__('', 'deca')),
        array('un-l-icon-uni49' => esc_html__('', 'deca')),
        array('un-l-icon-uni4A' => esc_html__('', 'deca')),
        array('un-l-icon-uni4B' => esc_html__('', 'deca')),
        array('un-l-icon-uni4C' => esc_html__('', 'deca')),
        array('un-l-icon-uni4D' => esc_html__('', 'deca')),
        array('un-l-icon-uni4E' => esc_html__('', 'deca')),
        array('un-l-icon-uni4F' => esc_html__('', 'deca')),
        array('un-l-icon-uni50' => esc_html__('', 'deca')),
        array('un-l-icon-uni51' => esc_html__('', 'deca')),
        array('un-l-icon-uni52' => esc_html__('', 'deca')),
        array('un-l-icon-uni53' => esc_html__('', 'deca')),
        array('un-l-icon-uni54' => esc_html__('', 'deca')),
        array('un-l-icon-uni55' => esc_html__('', 'deca')),
        array('un-l-icon-uni56' => esc_html__('', 'deca')),
        array('un-l-icon-uni57' => esc_html__('', 'deca')),
        array('un-l-icon-uni58' => esc_html__('', 'deca')),
        array('un-l-icon-uni59' => esc_html__('', 'deca')),
        array('un-l-icon-uni5A' => esc_html__('', 'deca')),
        array('un-l-icon-uni30' => esc_html__('', 'deca')),
        array('un-l-icon-uni31' => esc_html__('', 'deca')),
        array('un-l-icon-uni32' => esc_html__('', 'deca')),
        array('un-l-icon-uni33' => esc_html__('', 'deca')),
        array('un-l-icon-uni34' => esc_html__('', 'deca')),
        array('un-l-icon-uni35' => esc_html__('', 'deca')),
        array('un-l-icon-uni36' => esc_html__('', 'deca')),
        array('un-l-icon-uni37' => esc_html__('', 'deca')),
        array('un-l-icon-uni38' => esc_html__('', 'deca')),
        array('un-l-icon-uni39' => esc_html__('', 'deca')),
        array('un-l-icon-uni21' => esc_html__('', 'deca')),
        array('un-l-icon-uni22' => esc_html__('', 'deca')),
        array('un-l-icon-uni23' => esc_html__('', 'deca')),
        array('un-l-icon-uni24' => esc_html__('', 'deca')),
        array('un-l-icon-uni25' => esc_html__('', 'deca')),
        array('un-l-icon-uni26' => esc_html__('', 'deca')),
        array('un-l-icon-uni27' => esc_html__('', 'deca')),
        array('un-l-icon-uni28' => esc_html__('', 'deca')),
        array('un-l-icon-uni29' => esc_html__('', 'deca')),
        array('un-l-icon-uni2A' => esc_html__('', 'deca')),
        array('un-l-icon-uni2B' => esc_html__('', 'deca')),
        array('un-l-icon-uni2C' => esc_html__('', 'deca')),
        array('un-l-icon-uni2D' => esc_html__('', 'deca')),
        array('un-l-icon-uni2E' => esc_html__('', 'deca')),
        array('un-l-icon-uni2F' => esc_html__('', 'deca')),
        array('un-l-icon-uni3A' => esc_html__('', 'deca')),
        array('un-l-icon-uni3B' => esc_html__('', 'deca')),
        array('un-l-icon-uni3C' => esc_html__('', 'deca')),
        array('un-l-icon-uni3D' => esc_html__('', 'deca')),
        array('un-l-icon-uni3E' => esc_html__('', 'deca')),
        array('un-l-icon-uni3F' => esc_html__('', 'deca')),
        array('un-l-icon-uni40' => esc_html__('', 'deca')),
        array('un-l-icon-uni5B' => esc_html__('', 'deca')),
        array('un-l-icon-uni5D' => esc_html__('', 'deca')),
        array('un-l-icon-uni5E' => esc_html__('', 'deca')),
        array('un-l-icon-uni5F' => esc_html__('', 'deca')),
        array('un-l-icon-uni60' => esc_html__('', 'deca')),
        array('un-l-icon-uni7B' => esc_html__('', 'deca')),
        array('un-l-icon-uni7C' => esc_html__('', 'deca')),
        array('un-l-icon-uni7D' => esc_html__('', 'deca')),
        array('un-l-icon-uni7E' => esc_html__('', 'deca')),
        array('un-l-icon-uni5C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE088' => esc_html__('', 'deca')),
        array('un-l-icon-uniE089' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE08F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE090' => esc_html__('', 'deca')),
        array('un-l-icon-uniE091' => esc_html__('', 'deca')),
        array('un-l-icon-uniE092' => esc_html__('', 'deca')),
        array('un-l-icon-uniE093' => esc_html__('', 'deca')),
        array('un-l-icon-uniE094' => esc_html__('', 'deca')),
        array('un-l-icon-uniE095' => esc_html__('', 'deca')),
        array('un-l-icon-uniE096' => esc_html__('', 'deca')),
        array('un-l-icon-uniE097' => esc_html__('', 'deca')),
        array('un-l-icon-uniE098' => esc_html__('', 'deca')),
        array('un-l-icon-uniE099' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE09F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0A9' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0AF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B0' => esc_html__('', 'deca')),
        array('un-l-icon-uni7F' => esc_html__('', 'deca')),
        array('un-l-icon-uni80' => esc_html__('', 'deca')),
        array('un-l-icon-uni81' => esc_html__('', 'deca')),
        array('un-l-icon-uni82' => esc_html__('', 'deca')),
        array('un-l-icon-uni83' => esc_html__('', 'deca')),
        array('un-l-icon-uni84' => esc_html__('', 'deca')),
        array('un-l-icon-uni85' => esc_html__('', 'deca')),
        array('un-l-icon-uni86' => esc_html__('', 'deca')),
        array('un-l-icon-uni87' => esc_html__('', 'deca')),
        array('un-l-icon-uni88' => esc_html__('', 'deca')),
        array('un-l-icon-uni89' => esc_html__('', 'deca')),
        array('un-l-icon-uni8A' => esc_html__('', 'deca')),
        array('un-l-icon-uni8B' => esc_html__('', 'deca')),
        array('un-l-icon-uni8C' => esc_html__('', 'deca')),
        array('un-l-icon-uni8D' => esc_html__('', 'deca')),
        array('un-l-icon-uni8E' => esc_html__('', 'deca')),
        array('un-l-icon-uni8F' => esc_html__('', 'deca')),
        array('un-l-icon-uni90' => esc_html__('', 'deca')),
        array('un-l-icon-uni91' => esc_html__('', 'deca')),
        array('un-l-icon-uni92' => esc_html__('', 'deca')),
        array('un-l-icon-uni93' => esc_html__('', 'deca')),
        array('un-l-icon-uni94' => esc_html__('', 'deca')),
        array('un-l-icon-uni95' => esc_html__('', 'deca')),
        array('un-l-icon-uni96' => esc_html__('', 'deca')),
        array('un-l-icon-uni97' => esc_html__('', 'deca')),
        array('un-l-icon-uni98' => esc_html__('', 'deca')),
        array('un-l-icon-uni99' => esc_html__('', 'deca')),
        array('un-l-icon-uni9A' => esc_html__('', 'deca')),
        array('un-l-icon-uni9B' => esc_html__('', 'deca')),
        array('un-l-icon-uni9C' => esc_html__('', 'deca')),
        array('un-l-icon-uni9D' => esc_html__('', 'deca')),
        array('un-l-icon-uni9E' => esc_html__('', 'deca')),
        array('un-l-icon-uni9F' => esc_html__('', 'deca')),
        array('un-l-icon-uniA0' => esc_html__('', 'deca')),
        array('un-l-icon-uniA1' => esc_html__('', 'deca')),
        array('un-l-icon-uniA2' => esc_html__('', 'deca')),
        array('un-l-icon-uniA3' => esc_html__('', 'deca')),
        array('un-l-icon-uniA4' => esc_html__('', 'deca')),
        array('un-l-icon-uniA5' => esc_html__('', 'deca')),
        array('un-l-icon-uniA6' => esc_html__('', 'deca')),
        array('un-l-icon-uniA7' => esc_html__('', 'deca')),
        array('un-l-icon-uniA8' => esc_html__('', 'deca')),
        array('un-l-icon-uniA9' => esc_html__('', 'deca')),
        array('un-l-icon-uniAA' => esc_html__('', 'deca')),
        array('un-l-icon-uniAB' => esc_html__('', 'deca')),
        array('un-l-icon-uniAC' => esc_html__('', 'deca')),
        array('un-l-icon-uniAD' => esc_html__('', 'deca')),
        array('un-l-icon-uniAE' => esc_html__('', 'deca')),
        array('un-l-icon-uniAF' => esc_html__('', 'deca')),
        array('un-l-icon-uniB0' => esc_html__('', 'deca')),
        array('un-l-icon-uniB1' => esc_html__('', 'deca')),
        array('un-l-icon-uniB2' => esc_html__('', 'deca')),
        array('un-l-icon-uniB3' => esc_html__('', 'deca')),
        array('un-l-icon-uniB4' => esc_html__('', 'deca')),
        array('un-l-icon-uniB5' => esc_html__('', 'deca')),
        array('un-l-icon-uniB6' => esc_html__('', 'deca')),
        array('un-l-icon-uniB7' => esc_html__('', 'deca')),
        array('un-l-icon-uniB8' => esc_html__('', 'deca')),
        array('un-l-icon-uniB9' => esc_html__('', 'deca')),
        array('un-l-icon-uniBA' => esc_html__('', 'deca')),
        array('un-l-icon-uniBB' => esc_html__('', 'deca')),
        array('un-l-icon-uniBC' => esc_html__('', 'deca')),
        array('un-l-icon-uniBD' => esc_html__('', 'deca')),
        array('un-l-icon-uniBE' => esc_html__('', 'deca')),
        array('un-l-icon-uniBF' => esc_html__('', 'deca')),
        array('un-l-icon-uniC0' => esc_html__('', 'deca')),
        array('un-l-icon-uniC1' => esc_html__('', 'deca')),
        array('un-l-icon-uniC2' => esc_html__('', 'deca')),
        array('un-l-icon-uniC3' => esc_html__('', 'deca')),
        array('un-l-icon-uniC4' => esc_html__('', 'deca')),
        array('un-l-icon-uniC5' => esc_html__('', 'deca')),
        array('un-l-icon-uniC6' => esc_html__('', 'deca')),
        array('un-l-icon-uniC7' => esc_html__('', 'deca')),
        array('un-l-icon-uniC8' => esc_html__('', 'deca')),
        array('un-l-icon-uniC9' => esc_html__('', 'deca')),
        array('un-l-icon-uniCA' => esc_html__('', 'deca')),
        array('un-l-icon-uniCB' => esc_html__('', 'deca')),
        array('un-l-icon-uniCC' => esc_html__('', 'deca')),
        array('un-l-icon-uniCD' => esc_html__('', 'deca')),
        array('un-l-icon-uniCE' => esc_html__('', 'deca')),
        array('un-l-icon-uniCF' => esc_html__('', 'deca')),
        array('un-l-icon-uniD0' => esc_html__('', 'deca')),
        array('un-l-icon-uniD1' => esc_html__('', 'deca')),
        array('un-l-icon-uniD2' => esc_html__('', 'deca')),
        array('un-l-icon-uniD3' => esc_html__('', 'deca')),
        array('un-l-icon-uniD4' => esc_html__('', 'deca')),
        array('un-l-icon-uniD5' => esc_html__('', 'deca')),
        array('un-l-icon-uniD6' => esc_html__('', 'deca')),
        array('un-l-icon-uniD7' => esc_html__('', 'deca')),
        array('un-l-icon-uniD8' => esc_html__('', 'deca')),
        array('un-l-icon-uniD9' => esc_html__('', 'deca')),
        array('un-l-icon-uniDA' => esc_html__('', 'deca')),
        array('un-l-icon-uniDB' => esc_html__('', 'deca')),
        array('un-l-icon-uniDC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0B9' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0BF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0C9' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0CF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0D9' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0DF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E3' => esc_html__('', 'deca')),
        array('un-l-icon-uniDD' => esc_html__('', 'deca')),
        array('un-l-icon-uniDE' => esc_html__('', 'deca')),
        array('un-l-icon-uniDF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE9' => esc_html__('', 'deca')),
        array('un-l-icon-uniEA' => esc_html__('', 'deca')),
        array('un-l-icon-uniEB' => esc_html__('', 'deca')),
        array('un-l-icon-uniEC' => esc_html__('', 'deca')),
        array('un-l-icon-uniED' => esc_html__('', 'deca')),
        array('un-l-icon-uniEE' => esc_html__('', 'deca')),
        array('un-l-icon-uniEF' => esc_html__('', 'deca')),
        array('un-l-icon-uniF0' => esc_html__('', 'deca')),
        array('un-l-icon-uniF1' => esc_html__('', 'deca')),
        array('un-l-icon-uniF2' => esc_html__('', 'deca')),
        array('un-l-icon-uniF3' => esc_html__('', 'deca')),
        array('un-l-icon-uniF4' => esc_html__('', 'deca')),
        array('un-l-icon-uniF5' => esc_html__('', 'deca')),
        array('un-l-icon-uniF6' => esc_html__('', 'deca')),
        array('un-l-icon-uniF7' => esc_html__('', 'deca')),
        array('un-l-icon-uniF8' => esc_html__('', 'deca')),
        array('un-l-icon-uniF9' => esc_html__('', 'deca')),
        array('un-l-icon-uniFA' => esc_html__('', 'deca')),
        array('un-l-icon-uniFB' => esc_html__('', 'deca')),
        array('un-l-icon-uniFC' => esc_html__('', 'deca')),
        array('un-l-icon-uniFD' => esc_html__('', 'deca')),
        array('un-l-icon-uniFE' => esc_html__('', 'deca')),
        array('un-l-icon-uniFF' => esc_html__('', 'deca')),
        array('un-l-icon-uni100' => esc_html__('', 'deca')),
        array('un-l-icon-uni101' => esc_html__('', 'deca')),
        array('un-l-icon-uni102' => esc_html__('', 'deca')),
        array('un-l-icon-uni103' => esc_html__('', 'deca')),
        array('un-l-icon-uni104' => esc_html__('', 'deca')),
        array('un-l-icon-uni105' => esc_html__('', 'deca')),
        array('un-l-icon-uni106' => esc_html__('', 'deca')),
        array('un-l-icon-uni107' => esc_html__('', 'deca')),
        array('un-l-icon-uni108' => esc_html__('', 'deca')),
        array('un-l-icon-uni109' => esc_html__('', 'deca')),
        array('un-l-icon-uni10A' => esc_html__('', 'deca')),
        array('un-l-icon-uni10B' => esc_html__('', 'deca')),
        array('un-l-icon-uni10C' => esc_html__('', 'deca')),
        array('un-l-icon-uni10D' => esc_html__('', 'deca')),
        array('un-l-icon-uni10E' => esc_html__('', 'deca')),
        array('un-l-icon-uni10F' => esc_html__('', 'deca')),
        array('un-l-icon-uni110' => esc_html__('', 'deca')),
        array('un-l-icon-uni111' => esc_html__('', 'deca')),
        array('un-l-icon-uni112' => esc_html__('', 'deca')),
        array('un-l-icon-uni113' => esc_html__('', 'deca')),
        array('un-l-icon-uni114' => esc_html__('', 'deca')),
        array('un-l-icon-uni115' => esc_html__('', 'deca')),
        array('un-l-icon-uni116' => esc_html__('', 'deca')),
        array('un-l-icon-uni117' => esc_html__('', 'deca')),
        array('un-l-icon-uni118' => esc_html__('', 'deca')),
        array('un-l-icon-uni119' => esc_html__('', 'deca')),
        array('un-l-icon-uni11A' => esc_html__('', 'deca')),
        array('un-l-icon-uni11B' => esc_html__('', 'deca')),
        array('un-l-icon-uni11C' => esc_html__('', 'deca')),
        array('un-l-icon-uni11D' => esc_html__('', 'deca')),
        array('un-l-icon-uni11E' => esc_html__('', 'deca')),
        array('un-l-icon-uni11F' => esc_html__('', 'deca')),
        array('un-l-icon-uni120' => esc_html__('', 'deca')),
        array('un-l-icon-uni121' => esc_html__('', 'deca')),
        array('un-l-icon-uni122' => esc_html__('', 'deca')),
        array('un-l-icon-uni123' => esc_html__('', 'deca')),
        array('un-l-icon-uni124' => esc_html__('', 'deca')),
        array('un-l-icon-uni125' => esc_html__('', 'deca')),
        array('un-l-icon-uni126' => esc_html__('', 'deca')),
        array('un-l-icon-uni127' => esc_html__('', 'deca')),
        array('un-l-icon-uni128' => esc_html__('', 'deca')),
        array('un-l-icon-uni129' => esc_html__('', 'deca')),
        array('un-l-icon-uni12A' => esc_html__('', 'deca')),
        array('un-l-icon-uni12B' => esc_html__('', 'deca')),
        array('un-l-icon-uni12C' => esc_html__('', 'deca')),
        array('un-l-icon-uni12D' => esc_html__('', 'deca')),
        array('un-l-icon-uni12E' => esc_html__('', 'deca')),
        array('un-l-icon-uni12F' => esc_html__('', 'deca')),
        array('un-l-icon-uni130' => esc_html__('', 'deca')),
        array('un-l-icon-uni131' => esc_html__('', 'deca')),
        array('un-l-icon-uni132' => esc_html__('', 'deca')),
        array('un-l-icon-uni133' => esc_html__('', 'deca')),
        array('un-l-icon-uni134' => esc_html__('', 'deca')),
        array('un-l-icon-uni135' => esc_html__('', 'deca')),
        array('un-l-icon-uni136' => esc_html__('', 'deca')),
        array('un-l-icon-uni137' => esc_html__('', 'deca')),
        array('un-l-icon-uni138' => esc_html__('', 'deca')),
        array('un-l-icon-uni139' => esc_html__('', 'deca')),
        array('un-l-icon-uni13A' => esc_html__('', 'deca')),
        array('un-l-icon-uni13B' => esc_html__('', 'deca')),
        array('un-l-icon-uni13C' => esc_html__('', 'deca')),
        array('un-l-icon-uni13D' => esc_html__('', 'deca')),
        array('un-l-icon-uni13E' => esc_html__('', 'deca')),
        array('un-l-icon-uni13F' => esc_html__('', 'deca')),
        array('un-l-icon-uni140' => esc_html__('', 'deca')),
        array('un-l-icon-uni141' => esc_html__('', 'deca')),
        array('un-l-icon-uni142' => esc_html__('', 'deca')),
        array('un-l-icon-uni143' => esc_html__('', 'deca')),
        array('un-l-icon-uni144' => esc_html__('', 'deca')),
        array('un-l-icon-uni145' => esc_html__('', 'deca')),
        array('un-l-icon-uni146' => esc_html__('', 'deca')),
        array('un-l-icon-uni147' => esc_html__('', 'deca')),
        array('un-l-icon-uni148' => esc_html__('', 'deca')),
        array('un-l-icon-uni149' => esc_html__('', 'deca')),
        array('un-l-icon-uni14A' => esc_html__('', 'deca')),
        array('un-l-icon-uni14B' => esc_html__('', 'deca')),
        array('un-l-icon-uni14C' => esc_html__('', 'deca')),
        array('un-l-icon-uni14D' => esc_html__('', 'deca')),
        array('un-l-icon-uni14E' => esc_html__('', 'deca')),
        array('un-l-icon-uni14F' => esc_html__('', 'deca')),
        array('un-l-icon-uni150' => esc_html__('', 'deca')),
        array('un-l-icon-uni151' => esc_html__('', 'deca')),
        array('un-l-icon-uni152' => esc_html__('', 'deca')),
        array('un-l-icon-uni153' => esc_html__('', 'deca')),
        array('un-l-icon-uni154' => esc_html__('', 'deca')),
        array('un-l-icon-uni155' => esc_html__('', 'deca')),
        array('un-l-icon-uni156' => esc_html__('', 'deca')),
        array('un-l-icon-uni157' => esc_html__('', 'deca')),
        array('un-l-icon-uni158' => esc_html__('', 'deca')),
        array('un-l-icon-uni159' => esc_html__('', 'deca')),
        array('un-l-icon-uni15A' => esc_html__('', 'deca')),
        array('un-l-icon-uni15B' => esc_html__('', 'deca')),
        array('un-l-icon-uni15C' => esc_html__('', 'deca')),
        array('un-l-icon-uni15D' => esc_html__('', 'deca')),
        array('un-l-icon-uni15E' => esc_html__('', 'deca')),
        array('un-l-icon-uni15F' => esc_html__('', 'deca')),
        array('un-l-icon-uni160' => esc_html__('', 'deca')),
        array('un-l-icon-uni161' => esc_html__('', 'deca')),
        array('un-l-icon-uni162' => esc_html__('', 'deca')),
        array('un-l-icon-uni163' => esc_html__('', 'deca')),
        array('un-l-icon-uni164' => esc_html__('', 'deca')),
        array('un-l-icon-uni165' => esc_html__('', 'deca')),
        array('un-l-icon-uni166' => esc_html__('', 'deca')),
        array('un-l-icon-uni167' => esc_html__('', 'deca')),
        array('un-l-icon-uni168' => esc_html__('', 'deca')),
        array('un-l-icon-uni169' => esc_html__('', 'deca')),
        array('un-l-icon-uni16A' => esc_html__('', 'deca')),
        array('un-l-icon-uni16B' => esc_html__('', 'deca')),
        array('un-l-icon-uni16C' => esc_html__('', 'deca')),
        array('un-l-icon-uni16D' => esc_html__('', 'deca')),
        array('un-l-icon-uni16E' => esc_html__('', 'deca')),
        array('un-l-icon-uni16F' => esc_html__('', 'deca')),
        array('un-l-icon-uni170' => esc_html__('', 'deca')),
        array('un-l-icon-uni171' => esc_html__('', 'deca')),
        array('un-l-icon-uni172' => esc_html__('', 'deca')),
        array('un-l-icon-uni173' => esc_html__('', 'deca')),
        array('un-l-icon-uni174' => esc_html__('', 'deca')),
        array('un-l-icon-uni175' => esc_html__('', 'deca')),
        array('un-l-icon-uni176' => esc_html__('', 'deca')),
        array('un-l-icon-uni177' => esc_html__('', 'deca')),
        array('un-l-icon-uni178' => esc_html__('', 'deca')),
        array('un-l-icon-uni179' => esc_html__('', 'deca')),
        array('un-l-icon-uni17A' => esc_html__('', 'deca')),
        array('un-l-icon-uni17B' => esc_html__('', 'deca')),
        array('un-l-icon-uni17C' => esc_html__('', 'deca')),
        array('un-l-icon-uni17D' => esc_html__('', 'deca')),
        array('un-l-icon-uni17E' => esc_html__('', 'deca')),
        array('un-l-icon-uni17F' => esc_html__('', 'deca')),
        array('un-l-icon-uni180' => esc_html__('', 'deca')),
        array('un-l-icon-uni181' => esc_html__('', 'deca')),
        array('un-l-icon-uni182' => esc_html__('', 'deca')),
        array('un-l-icon-uni183' => esc_html__('', 'deca')),
        array('un-l-icon-uni184' => esc_html__('', 'deca')),
        array('un-l-icon-uni185' => esc_html__('', 'deca')),
        array('un-l-icon-uni186' => esc_html__('', 'deca')),
        array('un-l-icon-uni187' => esc_html__('', 'deca')),
        array('un-l-icon-uni188' => esc_html__('', 'deca')),
        array('un-l-icon-uni189' => esc_html__('', 'deca')),
        array('un-l-icon-uni18A' => esc_html__('', 'deca')),
        array('un-l-icon-uni18B' => esc_html__('', 'deca')),
        array('un-l-icon-uni18C' => esc_html__('', 'deca')),
        array('un-l-icon-uni18D' => esc_html__('', 'deca')),
        array('un-l-icon-uni18E' => esc_html__('', 'deca')),
        array('un-l-icon-uni18F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0E9' => esc_html__('', 'deca')),
        array('un-l-icon-uni190' => esc_html__('', 'deca')),
        array('un-l-icon-uni191' => esc_html__('', 'deca')),
        array('un-l-icon-uni192' => esc_html__('', 'deca')),
        array('un-l-icon-uni193' => esc_html__('', 'deca')),
        array('un-l-icon-uni194' => esc_html__('', 'deca')),
        array('un-l-icon-uni195' => esc_html__('', 'deca')),
        array('un-l-icon-uni196' => esc_html__('', 'deca')),
        array('un-l-icon-uni197' => esc_html__('', 'deca')),
        array('un-l-icon-uni198' => esc_html__('', 'deca')),
        array('un-l-icon-uni199' => esc_html__('', 'deca')),
        array('un-l-icon-uni19A' => esc_html__('', 'deca')),
        array('un-l-icon-uni19B' => esc_html__('', 'deca')),
        array('un-l-icon-uni19C' => esc_html__('', 'deca')),
        array('un-l-icon-uni19D' => esc_html__('', 'deca')),
        array('un-l-icon-uni19E' => esc_html__('', 'deca')),
        array('un-l-icon-uni19F' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A0' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A1' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A2' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A3' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A4' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A5' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A6' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A7' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A8' => esc_html__('', 'deca')),
        array('un-l-icon-uni1A9' => esc_html__('', 'deca')),
        array('un-l-icon-uni1AA' => esc_html__('', 'deca')),
        array('un-l-icon-uni1AB' => esc_html__('', 'deca')),
        array('un-l-icon-uni1AC' => esc_html__('', 'deca')),
        array('un-l-icon-uni1AD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0EA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0EB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0EC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0ED' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0EE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0EF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F0' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F1' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F2' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F3' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F4' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F5' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F6' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F7' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F8' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0F9' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FA' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FB' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FC' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FD' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FE' => esc_html__('', 'deca')),
        array('un-l-icon-uniE0FF' => esc_html__('', 'deca')),
        array('un-l-icon-uniE100' => esc_html__('', 'deca')),
        array('un-l-icon-uniE101' => esc_html__('', 'deca')),
        array('un-l-icon-uniE102' => esc_html__('', 'deca')),
        array('un-l-icon-uniE103' => esc_html__('', 'deca')),
        array('un-l-icon-uniE104' => esc_html__('', 'deca')),
        array('un-l-icon-uniE105' => esc_html__('', 'deca')),
        array('un-l-icon-uniE106' => esc_html__('', 'deca')),
        array('un-l-icon-uniE107' => esc_html__('', 'deca')),
        array('un-l-icon-uniE108' => esc_html__('', 'deca')),
        array('un-l-icon-uniE109' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE10F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE110' => esc_html__('', 'deca')),
        array('un-l-icon-uniE111' => esc_html__('', 'deca')),
        array('un-l-icon-uniE112' => esc_html__('', 'deca')),
        array('un-l-icon-uniE113' => esc_html__('', 'deca')),
        array('un-l-icon-uniE114' => esc_html__('', 'deca')),
        array('un-l-icon-uniE115' => esc_html__('', 'deca')),
        array('un-l-icon-uniE116' => esc_html__('', 'deca')),
        array('un-l-icon-uniE117' => esc_html__('', 'deca')),
        array('un-l-icon-uniE118' => esc_html__('', 'deca')),
        array('un-l-icon-uniE119' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE11F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE120' => esc_html__('', 'deca')),
        array('un-l-icon-uniE121' => esc_html__('', 'deca')),
        array('un-l-icon-uniE122' => esc_html__('', 'deca')),
        array('un-l-icon-uniE123' => esc_html__('', 'deca')),
        array('un-l-icon-uniE124' => esc_html__('', 'deca')),
        array('un-l-icon-uniE125' => esc_html__('', 'deca')),
        array('un-l-icon-uniE126' => esc_html__('', 'deca')),
        array('un-l-icon-uniE127' => esc_html__('', 'deca')),
        array('un-l-icon-uniE128' => esc_html__('', 'deca')),
        array('un-l-icon-uniE129' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12E' => esc_html__('', 'deca')),
        array('un-l-icon-uniE12F' => esc_html__('', 'deca')),
        array('un-l-icon-uniE130' => esc_html__('', 'deca')),
        array('un-l-icon-uniE131' => esc_html__('', 'deca')),
        array('un-l-icon-uniE132' => esc_html__('', 'deca')),
        array('un-l-icon-uniE133' => esc_html__('', 'deca')),
        array('un-l-icon-uniE134' => esc_html__('', 'deca')),
        array('un-l-icon-uniE135' => esc_html__('', 'deca')),
        array('un-l-icon-uniE136' => esc_html__('', 'deca')),
        array('un-l-icon-uniE137' => esc_html__('', 'deca')),
        array('un-l-icon-uniE138' => esc_html__('', 'deca')),
        array('un-l-icon-uniE139' => esc_html__('', 'deca')),
        array('un-l-icon-uniE13A' => esc_html__('', 'deca')),
        array('un-l-icon-uniE13B' => esc_html__('', 'deca')),
        array('un-l-icon-uniE13C' => esc_html__('', 'deca')),
        array('un-l-icon-uniE13D' => esc_html__('', 'deca')),
        array('un-l-icon-uniE13E' => esc_html__('', 'deca')),
    );

    return array_merge($icons, $linea_icons);

}


// FA Icons for iconpickers
add_filter( 'vc_iconpicker-type-fawe', 'un_iconpicker_type_fawe' );

function un_iconpicker_type_fawe( $icons ) {

    $fawe_icons = array(
        array('un-fa-icon-adjust' => esc_html__('', 'deca')),
        array('un-fa-icon-adn' => esc_html__('', 'deca')),
        array('un-fa-icon-align-center' => esc_html__('', 'deca')),
        array('un-fa-icon-align-justify' => esc_html__('', 'deca')),
        array('un-fa-icon-align-left' => esc_html__('', 'deca')),
        array('un-fa-icon-align-right' => esc_html__('', 'deca')),
        array('un-fa-icon-ambulance' => esc_html__('', 'deca')),
        array('un-fa-icon-anchor' => esc_html__('', 'deca')),
        array('un-fa-icon-android' => esc_html__('', 'deca')),
        array('un-fa-icon-angellist' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-double-down' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-double-left' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-double-right' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-double-up' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-down' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-left' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-right' => esc_html__('', 'deca')),
        array('un-fa-icon-angle-up' => esc_html__('', 'deca')),
        array('un-fa-icon-apple' => esc_html__('', 'deca')),
        array('un-fa-icon-archive' => esc_html__('', 'deca')),
        array('un-fa-icon-area-chart' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-down' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-left' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-o-down' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-o-left' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-o-right' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-o-up' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-right' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-circle-up' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-down' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-left' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-right' => esc_html__('', 'deca')),
        array('un-fa-icon-arrow-up' => esc_html__('', 'deca')),
        array('un-fa-icon-arrows' => esc_html__('', 'deca')),
        array('un-fa-icon-arrows-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-arrows-h' => esc_html__('', 'deca')),
        array('un-fa-icon-arrows-v' => esc_html__('', 'deca')),
        array('un-fa-icon-asterisk' => esc_html__('', 'deca')),
        array('un-fa-icon-at' => esc_html__('', 'deca')),
        array('un-fa-icon-automobile(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-backward' => esc_html__('', 'deca')),
        array('un-fa-icon-ban' => esc_html__('', 'deca')),
        array('un-fa-icon-bank(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-bar-chart' => esc_html__('', 'deca')),
        array('un-fa-icon-bar-chart-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-barcode' => esc_html__('', 'deca')),
        array('un-fa-icon-bars' => esc_html__('', 'deca')),
        array('un-fa-icon-bed' => esc_html__('', 'deca')),
        array('un-fa-icon-beer' => esc_html__('', 'deca')),
        array('un-fa-icon-behance' => esc_html__('', 'deca')),
        array('un-fa-icon-behance-square' => esc_html__('', 'deca')),
        array('un-fa-icon-bell' => esc_html__('', 'deca')),
        array('un-fa-icon-bell-o' => esc_html__('', 'deca')),
        array('un-fa-icon-bell-slash' => esc_html__('', 'deca')),
        array('un-fa-icon-bell-slash-o' => esc_html__('', 'deca')),
        array('un-fa-icon-bicycle' => esc_html__('', 'deca')),
        array('un-fa-icon-binoculars' => esc_html__('', 'deca')),
        array('un-fa-icon-birthday-cake' => esc_html__('', 'deca')),
        array('un-fa-icon-bitbucket' => esc_html__('', 'deca')),
        array('un-fa-icon-bitbucket-square' => esc_html__('', 'deca')),
        array('un-fa-icon-bitcoin(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-bold' => esc_html__('', 'deca')),
        array('un-fa-icon-bolt' => esc_html__('', 'deca')),
        array('un-fa-icon-bomb' => esc_html__('', 'deca')),
        array('un-fa-icon-book' => esc_html__('', 'deca')),
        array('un-fa-icon-bookmark' => esc_html__('', 'deca')),
        array('un-fa-icon-bookmark-o' => esc_html__('', 'deca')),
        array('un-fa-icon-briefcase' => esc_html__('', 'deca')),
        array('un-fa-icon-btc' => esc_html__('', 'deca')),
        array('un-fa-icon-bug' => esc_html__('', 'deca')),
        array('un-fa-icon-building' => esc_html__('', 'deca')),
        array('un-fa-icon-building-o' => esc_html__('', 'deca')),
        array('un-fa-icon-bullhorn' => esc_html__('', 'deca')),
        array('un-fa-icon-bullseye' => esc_html__('', 'deca')),
        array('un-fa-icon-bus' => esc_html__('', 'deca')),
        array('un-fa-icon-buysellads' => esc_html__('', 'deca')),
        array('un-fa-icon-cab(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-calculator' => esc_html__('', 'deca')),
        array('un-fa-icon-calendar' => esc_html__('', 'deca')),
        array('un-fa-icon-calendar-o' => esc_html__('', 'deca')),
        array('un-fa-icon-camera' => esc_html__('', 'deca')),
        array('un-fa-icon-camera-retro' => esc_html__('', 'deca')),
        array('un-fa-icon-car' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-down' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-left' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-right' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-square-o-down' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-square-o-left' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-square-o-right' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-square-o-up' => esc_html__('', 'deca')),
        array('un-fa-icon-caret-up' => esc_html__('', 'deca')),
        array('un-fa-icon-cart-arrow-down' => esc_html__('', 'deca')),
        array('un-fa-icon-cart-plus' => esc_html__('', 'deca')),
        array('un-fa-icon-cc' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-amex' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-discover' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-mastercard' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-paypal' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-stripe' => esc_html__('', 'deca')),
        array('un-fa-icon-cc-visa' => esc_html__('', 'deca')),
        array('un-fa-icon-certificate' => esc_html__('', 'deca')),
        array('un-fa-icon-chain(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-chain-broken' => esc_html__('', 'deca')),
        array('un-fa-icon-check' => esc_html__('', 'deca')),
        array('un-fa-icon-check-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-check-circle-o' => esc_html__('', 'deca')),
        array('un-fa-icon-check-square' => esc_html__('', 'deca')),
        array('un-fa-icon-check-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-circle-down' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-circle-left' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-circle-right' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-circle-up' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-down' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-left' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-right' => esc_html__('', 'deca')),
        array('un-fa-icon-chevron-up' => esc_html__('', 'deca')),
        array('un-fa-icon-child' => esc_html__('', 'deca')),
        array('un-fa-icon-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-circle-o' => esc_html__('', 'deca')),
        array('un-fa-icon-circle-o-notch' => esc_html__('', 'deca')),
        array('un-fa-icon-circle-thin' => esc_html__('', 'deca')),
        array('un-fa-icon-clipboard' => esc_html__('', 'deca')),
        array('un-fa-icon-clock-o' => esc_html__('', 'deca')),
        array('un-fa-icon-close(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-cloud' => esc_html__('', 'deca')),
        array('un-fa-icon-cloud-download' => esc_html__('', 'deca')),
        array('un-fa-icon-cloud-upload' => esc_html__('', 'deca')),
        array('un-fa-icon-cny(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-code' => esc_html__('', 'deca')),
        array('un-fa-icon-code-fork' => esc_html__('', 'deca')),
        array('un-fa-icon-codepen' => esc_html__('', 'deca')),
        array('un-fa-icon-coffee' => esc_html__('', 'deca')),
        array('un-fa-icon-cog' => esc_html__('', 'deca')),
        array('un-fa-icon-cogs' => esc_html__('', 'deca')),
        array('un-fa-icon-columns' => esc_html__('', 'deca')),
        array('un-fa-icon-comment' => esc_html__('', 'deca')),
        array('un-fa-icon-comment-o' => esc_html__('', 'deca')),
        array('un-fa-icon-comments' => esc_html__('', 'deca')),
        array('un-fa-icon-comments-o' => esc_html__('', 'deca')),
        array('un-fa-icon-compass' => esc_html__('', 'deca')),
        array('un-fa-icon-compress' => esc_html__('', 'deca')),
        array('un-fa-icon-connectdevelop' => esc_html__('', 'deca')),
        array('un-fa-icon-copy(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-copyright' => esc_html__('', 'deca')),
        array('un-fa-icon-credit-card' => esc_html__('', 'deca')),
        array('un-fa-icon-crop' => esc_html__('', 'deca')),
        array('un-fa-icon-crosshairs' => esc_html__('', 'deca')),
        array('un-fa-icon-css3' => esc_html__('', 'deca')),
        array('un-fa-icon-cube' => esc_html__('', 'deca')),
        array('un-fa-icon-cubes' => esc_html__('', 'deca')),
        array('un-fa-icon-cut(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-cutlery' => esc_html__('', 'deca')),
        array('un-fa-icon-dashboard(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-dashcube' => esc_html__('', 'deca')),
        array('un-fa-icon-database' => esc_html__('', 'deca')),
        array('un-fa-icon-dedent(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-delicious' => esc_html__('', 'deca')),
        array('un-fa-icon-desktop' => esc_html__('', 'deca')),
        array('un-fa-icon-deviantart' => esc_html__('', 'deca')),
        array('un-fa-icon-diamond' => esc_html__('', 'deca')),
        array('un-fa-icon-digg' => esc_html__('', 'deca')),
        array('un-fa-icon-dollar(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-dot-circle-o' => esc_html__('', 'deca')),
        array('un-fa-icon-download' => esc_html__('', 'deca')),
        array('un-fa-icon-dribbble' => esc_html__('', 'deca')),
        array('un-fa-icon-dropbox' => esc_html__('', 'deca')),
        array('un-fa-icon-drupal' => esc_html__('', 'deca')),
        array('un-fa-icon-edit(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-eject' => esc_html__('', 'deca')),
        array('un-fa-icon-ellipsis-h' => esc_html__('', 'deca')),
        array('un-fa-icon-ellipsis-v' => esc_html__('', 'deca')),
        array('un-fa-icon-empire' => esc_html__('', 'deca')),
        array('un-fa-icon-envelope' => esc_html__('', 'deca')),
        array('un-fa-icon-envelope-o' => esc_html__('', 'deca')),
        array('un-fa-icon-envelope-square' => esc_html__('', 'deca')),
        array('un-fa-icon-eraser' => esc_html__('', 'deca')),
        array('un-fa-icon-eur' => esc_html__('', 'deca')),
        array('un-fa-icon-euro(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-exchange' => esc_html__('', 'deca')),
        array('un-fa-icon-exclamation' => esc_html__('', 'deca')),
        array('un-fa-icon-exclamation-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-exclamation-triangle' => esc_html__('', 'deca')),
        array('un-fa-icon-expand' => esc_html__('', 'deca')),
        array('un-fa-icon-external-link' => esc_html__('', 'deca')),
        array('un-fa-icon-external-link-square' => esc_html__('', 'deca')),
        array('un-fa-icon-eye' => esc_html__('', 'deca')),
        array('un-fa-icon-eye-slash' => esc_html__('', 'deca')),
        array('un-fa-icon-eyedropper' => esc_html__('', 'deca')),
        array('un-fa-icon-facebook' => esc_html__('', 'deca')),
        array('un-fa-icon-facebook-f(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-facebook-official' => esc_html__('', 'deca')),
        array('un-fa-icon-facebook-square' => esc_html__('', 'deca')),
        array('un-fa-icon-fast-backward' => esc_html__('', 'deca')),
        array('un-fa-icon-fast-forward' => esc_html__('', 'deca')),
        array('un-fa-icon-fax' => esc_html__('', 'deca')),
        array('un-fa-icon-female' => esc_html__('', 'deca')),
        array('un-fa-icon-fighter-jet' => esc_html__('', 'deca')),
        array('un-fa-icon-file' => esc_html__('', 'deca')),
        array('un-fa-icon-file-archive-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-audio-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-code-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-excel-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-image-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-movie-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-file-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-pdf-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-photo-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-file-picture-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-file-powerpoint-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-sound-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-file-text' => esc_html__('', 'deca')),
        array('un-fa-icon-file-text-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-video-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-word-o' => esc_html__('', 'deca')),
        array('un-fa-icon-file-zip-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-files-o' => esc_html__('', 'deca')),
        array('un-fa-icon-film' => esc_html__('', 'deca')),
        array('un-fa-icon-filter' => esc_html__('', 'deca')),
        array('un-fa-icon-fire' => esc_html__('', 'deca')),
        array('un-fa-icon-fire-extinguisher' => esc_html__('', 'deca')),
        array('un-fa-icon-flag' => esc_html__('', 'deca')),
        array('un-fa-icon-flag-checkered' => esc_html__('', 'deca')),
        array('un-fa-icon-flag-o' => esc_html__('', 'deca')),
        array('un-fa-icon-flash(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-flask' => esc_html__('', 'deca')),
        array('un-fa-icon-flickr' => esc_html__('', 'deca')),
        array('un-fa-icon-floppy-o' => esc_html__('', 'deca')),
        array('un-fa-icon-folder' => esc_html__('', 'deca')),
        array('un-fa-icon-folder-o' => esc_html__('', 'deca')),
        array('un-fa-icon-folder-open' => esc_html__('', 'deca')),
        array('un-fa-icon-folder-open-o' => esc_html__('', 'deca')),
        array('un-fa-icon-font' => esc_html__('', 'deca')),
        array('un-fa-icon-forumbee' => esc_html__('', 'deca')),
        array('un-fa-icon-forward' => esc_html__('', 'deca')),
        array('un-fa-icon-foursquare' => esc_html__('', 'deca')),
        array('un-fa-icon-frown-o' => esc_html__('', 'deca')),
        array('un-fa-icon-futbol-o' => esc_html__('', 'deca')),
        array('un-fa-icon-gamepad' => esc_html__('', 'deca')),
        array('un-fa-icon-gavel' => esc_html__('', 'deca')),
        array('un-fa-icon-gbp' => esc_html__('', 'deca')),
        array('un-fa-icon-ge(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-gear(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-gears(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-genderless(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-gift' => esc_html__('', 'deca')),
        array('un-fa-icon-git' => esc_html__('', 'deca')),
        array('un-fa-icon-git-square' => esc_html__('', 'deca')),
        array('un-fa-icon-github' => esc_html__('', 'deca')),
        array('un-fa-icon-github-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-github-square' => esc_html__('', 'deca')),
        array('un-fa-icon-gittip(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-glass' => esc_html__('', 'deca')),
        array('un-fa-icon-globe' => esc_html__('', 'deca')),
        array('un-fa-icon-google' => esc_html__('', 'deca')),
        array('un-fa-icon-google-plus' => esc_html__('', 'deca')),
        array('un-fa-icon-google-plus-square' => esc_html__('', 'deca')),
        array('un-fa-icon-google-wallet' => esc_html__('', 'deca')),
        array('un-fa-icon-graduation-cap' => esc_html__('', 'deca')),
        array('un-fa-icon-gratipay' => esc_html__('', 'deca')),
        array('un-fa-icon-group(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-h-square' => esc_html__('', 'deca')),
        array('un-fa-icon-hacker-news' => esc_html__('', 'deca')),
        array('un-fa-icon-hand-o-down' => esc_html__('', 'deca')),
        array('un-fa-icon-hand-o-left' => esc_html__('', 'deca')),
        array('un-fa-icon-hand-o-right' => esc_html__('', 'deca')),
        array('un-fa-icon-hand-o-up' => esc_html__('', 'deca')),
        array('un-fa-icon-hdd-o' => esc_html__('', 'deca')),
        array('un-fa-icon-header' => esc_html__('', 'deca')),
        array('un-fa-icon-headphones' => esc_html__('', 'deca')),
        array('un-fa-icon-heart' => esc_html__('', 'deca')),
        array('un-fa-icon-heart-o' => esc_html__('', 'deca')),
        array('un-fa-icon-heartbeat' => esc_html__('', 'deca')),
        array('un-fa-icon-history' => esc_html__('', 'deca')),
        array('un-fa-icon-home' => esc_html__('', 'deca')),
        array('un-fa-icon-hospital-o' => esc_html__('', 'deca')),
        array('un-fa-icon-hotel(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-html5' => esc_html__('', 'deca')),
        array('un-fa-icon-ils' => esc_html__('', 'deca')),
        array('un-fa-icon-image(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-inbox' => esc_html__('', 'deca')),
        array('un-fa-icon-indent' => esc_html__('', 'deca')),
        array('un-fa-icon-info' => esc_html__('', 'deca')),
        array('un-fa-icon-info-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-inr' => esc_html__('', 'deca')),
        array('un-fa-icon-instagram' => esc_html__('', 'deca')),
        array('un-fa-icon-institution(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-ioxhost' => esc_html__('', 'deca')),
        array('un-fa-icon-italic' => esc_html__('', 'deca')),
        array('un-fa-icon-joomla' => esc_html__('', 'deca')),
        array('un-fa-icon-jpy' => esc_html__('', 'deca')),
        array('un-fa-icon-jsfiddle' => esc_html__('', 'deca')),
        array('un-fa-icon-key' => esc_html__('', 'deca')),
        array('un-fa-icon-keyboard-o' => esc_html__('', 'deca')),
        array('un-fa-icon-krw' => esc_html__('', 'deca')),
        array('un-fa-icon-language' => esc_html__('', 'deca')),
        array('un-fa-icon-laptop' => esc_html__('', 'deca')),
        array('un-fa-icon-lastfm' => esc_html__('', 'deca')),
        array('un-fa-icon-lastfm-square' => esc_html__('', 'deca')),
        array('un-fa-icon-leaf' => esc_html__('', 'deca')),
        array('un-fa-icon-leanpub' => esc_html__('', 'deca')),
        array('un-fa-icon-legal(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-lemon-o' => esc_html__('', 'deca')),
        array('un-fa-icon-level-down' => esc_html__('', 'deca')),
        array('un-fa-icon-level-up' => esc_html__('', 'deca')),
        array('un-fa-icon-life-bouy(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-life-buoy(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-life-ring' => esc_html__('', 'deca')),
        array('un-fa-icon-life-saver(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-lightbulb-o' => esc_html__('', 'deca')),
        array('un-fa-icon-line-chart' => esc_html__('', 'deca')),
        array('un-fa-icon-link' => esc_html__('', 'deca')),
        array('un-fa-icon-linkedin' => esc_html__('', 'deca')),
        array('un-fa-icon-linkedin-square' => esc_html__('', 'deca')),
        array('un-fa-icon-linux' => esc_html__('', 'deca')),
        array('un-fa-icon-list' => esc_html__('', 'deca')),
        array('un-fa-icon-list-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-list-ol' => esc_html__('', 'deca')),
        array('un-fa-icon-list-ul' => esc_html__('', 'deca')),
        array('un-fa-icon-location-arrow' => esc_html__('', 'deca')),
        array('un-fa-icon-lock' => esc_html__('', 'deca')),
        array('un-fa-icon-long-arrow-down' => esc_html__('', 'deca')),
        array('un-fa-icon-long-arrow-left' => esc_html__('', 'deca')),
        array('un-fa-icon-long-arrow-right' => esc_html__('', 'deca')),
        array('un-fa-icon-long-arrow-up' => esc_html__('', 'deca')),
        array('un-fa-icon-magic' => esc_html__('', 'deca')),
        array('un-fa-icon-magnet' => esc_html__('', 'deca')),
        array('un-fa-icon-mail-forward(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-mail-reply(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-mail-reply-all(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-male' => esc_html__('', 'deca')),
        array('un-fa-icon-map-marker' => esc_html__('', 'deca')),
        array('un-fa-icon-mars' => esc_html__('', 'deca')),
        array('un-fa-icon-mars-double' => esc_html__('', 'deca')),
        array('un-fa-icon-mars-stroke' => esc_html__('', 'deca')),
        array('un-fa-icon-mars-stroke-h' => esc_html__('', 'deca')),
        array('un-fa-icon-mars-stroke-v' => esc_html__('', 'deca')),
        array('un-fa-icon-maxcdn' => esc_html__('', 'deca')),
        array('un-fa-icon-meanpath' => esc_html__('', 'deca')),
        array('un-fa-icon-medium' => esc_html__('', 'deca')),
        array('un-fa-icon-medkit' => esc_html__('', 'deca')),
        array('un-fa-icon-meh-o' => esc_html__('', 'deca')),
        array('un-fa-icon-mercury' => esc_html__('', 'deca')),
        array('un-fa-icon-microphone' => esc_html__('', 'deca')),
        array('un-fa-icon-microphone-slash' => esc_html__('', 'deca')),
        array('un-fa-icon-minus' => esc_html__('', 'deca')),
        array('un-fa-icon-minus-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-minus-square' => esc_html__('', 'deca')),
        array('un-fa-icon-minus-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-mobile' => esc_html__('', 'deca')),
        array('un-fa-icon-mobile-phone(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-money' => esc_html__('', 'deca')),
        array('un-fa-icon-moon-o' => esc_html__('', 'deca')),
        array('un-fa-icon-mortar-board(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-motorcycle' => esc_html__('', 'deca')),
        array('un-fa-icon-music' => esc_html__('', 'deca')),
        array('un-fa-icon-navicon(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-neuter' => esc_html__('', 'deca')),
        array('un-fa-icon-newspaper-o' => esc_html__('', 'deca')),
        array('un-fa-icon-openid' => esc_html__('', 'deca')),
        array('un-fa-icon-outdent' => esc_html__('', 'deca')),
        array('un-fa-icon-pagelines' => esc_html__('', 'deca')),
        array('un-fa-icon-paint-brush' => esc_html__('', 'deca')),
        array('un-fa-icon-paper-plane' => esc_html__('', 'deca')),
        array('un-fa-icon-paper-plane-o' => esc_html__('', 'deca')),
        array('un-fa-icon-paperclip' => esc_html__('', 'deca')),
        array('un-fa-icon-paragraph' => esc_html__('', 'deca')),
        array('un-fa-icon-paste(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-pause' => esc_html__('', 'deca')),
        array('un-fa-icon-paw' => esc_html__('', 'deca')),
        array('un-fa-icon-paypal' => esc_html__('', 'deca')),
        array('un-fa-icon-pencil' => esc_html__('', 'deca')),
        array('un-fa-icon-pencil-square' => esc_html__('', 'deca')),
        array('un-fa-icon-pencil-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-phone' => esc_html__('', 'deca')),
        array('un-fa-icon-phone-square' => esc_html__('', 'deca')),
        array('un-fa-icon-photo(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-picture-o' => esc_html__('', 'deca')),
        array('un-fa-icon-pie-chart' => esc_html__('', 'deca')),
        array('un-fa-icon-pied-piper' => esc_html__('', 'deca')),
        array('un-fa-icon-pied-piper-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-pinterest' => esc_html__('', 'deca')),
        array('un-fa-icon-pinterest-p' => esc_html__('', 'deca')),
        array('un-fa-icon-pinterest-square' => esc_html__('', 'deca')),
        array('un-fa-icon-plane' => esc_html__('', 'deca')),
        array('un-fa-icon-play' => esc_html__('', 'deca')),
        array('un-fa-icon-play-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-play-circle-o' => esc_html__('', 'deca')),
        array('un-fa-icon-plug' => esc_html__('', 'deca')),
        array('un-fa-icon-plus' => esc_html__('', 'deca')),
        array('un-fa-icon-plus-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-plus-square' => esc_html__('', 'deca')),
        array('un-fa-icon-plus-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-power-off' => esc_html__('', 'deca')),
        array('un-fa-icon-print' => esc_html__('', 'deca')),
        array('un-fa-icon-puzzle-piece' => esc_html__('', 'deca')),
        array('un-fa-icon-qq' => esc_html__('', 'deca')),
        array('un-fa-icon-qrcode' => esc_html__('', 'deca')),
        array('un-fa-icon-question' => esc_html__('', 'deca')),
        array('un-fa-icon-question-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-quote-left' => esc_html__('', 'deca')),
        array('un-fa-icon-quote-right' => esc_html__('', 'deca')),
        array('un-fa-icon-ra(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-random' => esc_html__('', 'deca')),
        array('un-fa-icon-rebel' => esc_html__('', 'deca')),
        array('un-fa-icon-recycle' => esc_html__('', 'deca')),
        array('un-fa-icon-reddit' => esc_html__('', 'deca')),
        array('un-fa-icon-reddit-square' => esc_html__('', 'deca')),
        array('un-fa-icon-refresh' => esc_html__('', 'deca')),
        array('un-fa-icon-remove(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-renren' => esc_html__('', 'deca')),
        array('un-fa-icon-reorder(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-repeat' => esc_html__('', 'deca')),
        array('un-fa-icon-reply' => esc_html__('', 'deca')),
        array('un-fa-icon-reply-all' => esc_html__('', 'deca')),
        array('un-fa-icon-retweet' => esc_html__('', 'deca')),
        array('un-fa-icon-rmb(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-road' => esc_html__('', 'deca')),
        array('un-fa-icon-rocket' => esc_html__('', 'deca')),
        array('un-fa-icon-rotate-left(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-rotate-right(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-rouble(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-rss' => esc_html__('', 'deca')),
        array('un-fa-icon-rss-square' => esc_html__('', 'deca')),
        array('un-fa-icon-rub' => esc_html__('', 'deca')),
        array('un-fa-icon-ruble(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-rupee(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-save(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-scissors' => esc_html__('', 'deca')),
        array('un-fa-icon-search' => esc_html__('', 'deca')),
        array('un-fa-icon-search-minus' => esc_html__('', 'deca')),
        array('un-fa-icon-search-plus' => esc_html__('', 'deca')),
        array('un-fa-icon-sellsy' => esc_html__('', 'deca')),
        array('un-fa-icon-send(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-send-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-server' => esc_html__('', 'deca')),
        array('un-fa-icon-share' => esc_html__('', 'deca')),
        array('un-fa-icon-share-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-share-alt-square' => esc_html__('', 'deca')),
        array('un-fa-icon-share-square' => esc_html__('', 'deca')),
        array('un-fa-icon-share-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-shekel(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-sheqel(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-shield' => esc_html__('', 'deca')),
        array('un-fa-icon-ship' => esc_html__('', 'deca')),
        array('un-fa-icon-shirtsinbulk' => esc_html__('', 'deca')),
        array('un-fa-icon-shopping-cart' => esc_html__('', 'deca')),
        array('un-fa-icon-sign-in' => esc_html__('', 'deca')),
        array('un-fa-icon-sign-out' => esc_html__('', 'deca')),
        array('un-fa-icon-signal' => esc_html__('', 'deca')),
        array('un-fa-icon-simplybuilt' => esc_html__('', 'deca')),
        array('un-fa-icon-sitemap' => esc_html__('', 'deca')),
        array('un-fa-icon-skyatlas' => esc_html__('', 'deca')),
        array('un-fa-icon-skype' => esc_html__('', 'deca')),
        array('un-fa-icon-slack' => esc_html__('', 'deca')),
        array('un-fa-icon-sliders' => esc_html__('', 'deca')),
        array('un-fa-icon-slideshare' => esc_html__('', 'deca')),
        array('un-fa-icon-smile-o' => esc_html__('', 'deca')),
        array('un-fa-icon-soccer-ball-o(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-sort' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-alpha-asc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-alpha-desc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-amount-asc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-amount-desc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-asc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-desc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-down(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-numeric-asc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-numeric-desc' => esc_html__('', 'deca')),
        array('un-fa-icon-sort-up(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-soundcloud' => esc_html__('', 'deca')),
        array('un-fa-icon-space-shuttle' => esc_html__('', 'deca')),
        array('un-fa-icon-spinner' => esc_html__('', 'deca')),
        array('un-fa-icon-spoon' => esc_html__('', 'deca')),
        array('un-fa-icon-spotify' => esc_html__('', 'deca')),
        array('un-fa-icon-square' => esc_html__('', 'deca')),
        array('un-fa-icon-square-o' => esc_html__('', 'deca')),
        array('un-fa-icon-stack-exchange' => esc_html__('', 'deca')),
        array('un-fa-icon-stack-overflow' => esc_html__('', 'deca')),
        array('un-fa-icon-star' => esc_html__('', 'deca')),
        array('un-fa-icon-star-half' => esc_html__('', 'deca')),
        array('un-fa-icon-star-half-empty(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-star-half-full(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-star-half-o' => esc_html__('', 'deca')),
        array('un-fa-icon-star-o' => esc_html__('', 'deca')),
        array('un-fa-icon-steam' => esc_html__('', 'deca')),
        array('un-fa-icon-steam-square' => esc_html__('', 'deca')),
        array('un-fa-icon-step-backward' => esc_html__('', 'deca')),
        array('un-fa-icon-step-forward' => esc_html__('', 'deca')),
        array('un-fa-icon-stethoscope' => esc_html__('', 'deca')),
        array('un-fa-icon-stop' => esc_html__('', 'deca')),
        array('un-fa-icon-street-view' => esc_html__('', 'deca')),
        array('un-fa-icon-strikethrough' => esc_html__('', 'deca')),
        array('un-fa-icon-stumbleupon' => esc_html__('', 'deca')),
        array('un-fa-icon-stumbleupon-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-subscript' => esc_html__('', 'deca')),
        array('un-fa-icon-subway' => esc_html__('', 'deca')),
        array('un-fa-icon-suitcase' => esc_html__('', 'deca')),
        array('un-fa-icon-sun-o' => esc_html__('', 'deca')),
        array('un-fa-icon-superscript' => esc_html__('', 'deca')),
        array('un-fa-icon-support(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-table' => esc_html__('', 'deca')),
        array('un-fa-icon-tablet' => esc_html__('', 'deca')),
        array('un-fa-icon-tachometer' => esc_html__('', 'deca')),
        array('un-fa-icon-tag' => esc_html__('', 'deca')),
        array('un-fa-icon-tags' => esc_html__('', 'deca')),
        array('un-fa-icon-tasks' => esc_html__('', 'deca')),
        array('un-fa-icon-taxi' => esc_html__('', 'deca')),
        array('un-fa-icon-tencent-weibo' => esc_html__('', 'deca')),
        array('un-fa-icon-terminal' => esc_html__('', 'deca')),
        array('un-fa-icon-text-height' => esc_html__('', 'deca')),
        array('un-fa-icon-text-width' => esc_html__('', 'deca')),
        array('un-fa-icon-th' => esc_html__('', 'deca')),
        array('un-fa-icon-th-large' => esc_html__('', 'deca')),
        array('un-fa-icon-th-list' => esc_html__('', 'deca')),
        array('un-fa-icon-thumb-tack' => esc_html__('', 'deca')),
        array('un-fa-icon-thumbs-down' => esc_html__('', 'deca')),
        array('un-fa-icon-thumbs-o-down' => esc_html__('', 'deca')),
        array('un-fa-icon-thumbs-o-up' => esc_html__('', 'deca')),
        array('un-fa-icon-thumbs-up' => esc_html__('', 'deca')),
        array('un-fa-icon-ticket' => esc_html__('', 'deca')),
        array('un-fa-icon-times' => esc_html__('', 'deca')),
        array('un-fa-icon-times-circle' => esc_html__('', 'deca')),
        array('un-fa-icon-times-circle-o' => esc_html__('', 'deca')),
        array('un-fa-icon-tint' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-down(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-left(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-off' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-on' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-right(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-toggle-up(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-train' => esc_html__('', 'deca')),
        array('un-fa-icon-transgender' => esc_html__('', 'deca')),
        array('un-fa-icon-transgender-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-trash' => esc_html__('', 'deca')),
        array('un-fa-icon-trash-o' => esc_html__('', 'deca')),
        array('un-fa-icon-tree' => esc_html__('', 'deca')),
        array('un-fa-icon-trello' => esc_html__('', 'deca')),
        array('un-fa-icon-trophy' => esc_html__('', 'deca')),
        array('un-fa-icon-truck' => esc_html__('', 'deca')),
        array('un-fa-icon-try' => esc_html__('', 'deca')),
        array('un-fa-icon-tty' => esc_html__('', 'deca')),
        array('un-fa-icon-tumblr' => esc_html__('', 'deca')),
        array('un-fa-icon-tumblr-square' => esc_html__('', 'deca')),
        array('un-fa-icon-turkish-lira(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-twitch' => esc_html__('', 'deca')),
        array('un-fa-icon-twitter' => esc_html__('', 'deca')),
        array('un-fa-icon-twitter-square' => esc_html__('', 'deca')),
        array('un-fa-icon-umbrella' => esc_html__('', 'deca')),
        array('un-fa-icon-underline' => esc_html__('', 'deca')),
        array('un-fa-icon-undo' => esc_html__('', 'deca')),
        array('un-fa-icon-university' => esc_html__('', 'deca')),
        array('un-fa-icon-unlink(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-unlock' => esc_html__('', 'deca')),
        array('un-fa-icon-unlock-alt' => esc_html__('', 'deca')),
        array('un-fa-icon-unsorted(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-upload' => esc_html__('', 'deca')),
        array('un-fa-icon-usd' => esc_html__('', 'deca')),
        array('un-fa-icon-user' => esc_html__('', 'deca')),
        array('un-fa-icon-user-md' => esc_html__('', 'deca')),
        array('un-fa-icon-user-plus' => esc_html__('', 'deca')),
        array('un-fa-icon-user-secret' => esc_html__('', 'deca')),
        array('un-fa-icon-user-times' => esc_html__('', 'deca')),
        array('un-fa-icon-users' => esc_html__('', 'deca')),
        array('un-fa-icon-venus' => esc_html__('', 'deca')),
        array('un-fa-icon-venus-double' => esc_html__('', 'deca')),
        array('un-fa-icon-venus-mars' => esc_html__('', 'deca')),
        array('un-fa-icon-viacoin' => esc_html__('', 'deca')),
        array('un-fa-icon-video-camera' => esc_html__('', 'deca')),
        array('un-fa-icon-vimeo-square' => esc_html__('', 'deca')),
        array('un-fa-icon-vine' => esc_html__('', 'deca')),
        array('un-fa-icon-vk' => esc_html__('', 'deca')),
        array('un-fa-icon-volume-down' => esc_html__('', 'deca')),
        array('un-fa-icon-volume-off' => esc_html__('', 'deca')),
        array('un-fa-icon-volume-up' => esc_html__('', 'deca')),
        array('un-fa-icon-warning(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-wechat(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-weibo' => esc_html__('', 'deca')),
        array('un-fa-icon-weixin' => esc_html__('', 'deca')),
        array('un-fa-icon-whatsapp' => esc_html__('', 'deca')),
        array('un-fa-icon-wheelchair' => esc_html__('', 'deca')),
        array('un-fa-icon-wifi' => esc_html__('', 'deca')),
        array('un-fa-icon-windows' => esc_html__('', 'deca')),
        array('un-fa-icon-won(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-wordpress' => esc_html__('', 'deca')),
        array('un-fa-icon-wrench' => esc_html__('', 'deca')),
        array('un-fa-icon-xing' => esc_html__('', 'deca')),
        array('un-fa-icon-xing-square' => esc_html__('', 'deca')),
        array('un-fa-icon-yahoo' => esc_html__('', 'deca')),
        array('un-fa-icon-yelp' => esc_html__('', 'deca')),
        array('un-fa-icon-yen(alias)' => esc_html__('', 'deca')),
        array('un-fa-icon-youtube' => esc_html__('', 'deca')),
        array('un-fa-icon-youtube-play' => esc_html__('', 'deca')),
        array('un-fa-icon-youtube-square' => esc_html__('', 'deca')),
    );

   return array_merge($icons, $fawe_icons);
    
}


// Include Custom Mimes on upload system
add_filter( 'mime_types', 'un_custom_upload_mimes' );

function un_custom_upload_mimes ($mimes) { 

	$mimes['svg'] = 'image/svg+xml';
	
	return $mimes;

}

